-- =====================================================
-- REMOVER PERMISSÕES DE CRIAÇÃO DE CUPONS PARA PARTNERS-MEDIA
-- =====================================================
-- Este script remove as permissões de criação de cupons para partners-media
-- Apenas owners e admins poderão criar cupons a partir de agora
-- Execute este script no Supabase SQL Editor

-- =====================================================
-- 1. REMOVER POLÍTICA DE CRIAÇÃO PARA PARTNERS-MEDIA
-- =====================================================

-- Remover a política que permite partners-media criar cupons
DROP POLICY IF EXISTS "Allow partners-media to create coupons for their brand" ON generated_coupons;

-- =====================================================
-- 2. CRIAR NOVA POLÍTICA APENAS PARA OWNERS E ADMINS
-- =====================================================

-- Permitir apenas owners e admins criarem cupons
CREATE POLICY "Allow owners and admins to create coupons"
ON generated_coupons
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM user_profiles 
    WHERE user_profiles.id = auth.uid() 
    AND user_profiles.role IN ('owner', 'admin')
    AND user_profiles.approved = true
  )
  AND created_by = auth.uid()
);

-- =====================================================
-- 3. ATUALIZAR POLÍTICA DE ATUALIZAÇÃO (se existir)
-- =====================================================

-- Remover política de atualização para partners-media (se existir)
DROP POLICY IF EXISTS "Allow partners-media to update their coupons" ON generated_coupons;

-- Permitir apenas owners e admins atualizarem cupons
CREATE POLICY "Allow owners and admins to update coupons"
ON generated_coupons
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM user_profiles 
    WHERE user_profiles.id = auth.uid() 
    AND user_profiles.role IN ('owner', 'admin')
    AND user_profiles.approved = true
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM user_profiles 
    WHERE user_profiles.id = auth.uid() 
    AND user_profiles.role IN ('owner', 'admin')
    AND user_profiles.approved = true
  )
);

-- =====================================================
-- 4. MANTER POLÍTICAS DE VISUALIZAÇÃO
-- =====================================================

-- As políticas de visualização para partners-media devem ser mantidas
-- Eles ainda podem ver os cupons da sua marca atribuída

-- Verificar se a política de leitura para partners-media existe
-- (não precisa ser alterada, apenas verificação)

-- =====================================================
-- 5. COMENTÁRIOS E DOCUMENTAÇÃO
-- =====================================================

-- Atualizar comentários da tabela
COMMENT ON TABLE generated_coupons IS 'Stores coupons generated by owners and admins. Partners-media can only view coupons for their assigned brands.';

-- =====================================================
-- 6. VERIFICAÇÃO DAS POLÍTICAS
-- =====================================================

-- Verificar as políticas ativas na tabela
SELECT 
  schemaname,
  tablename,
  policyname,
  permissive,
  roles,
  cmd,
  qual,
  with_check
FROM pg_policies 
WHERE tablename = 'generated_coupons'
ORDER BY policyname;

-- =====================================================
-- 7. TESTE DAS PERMISSÕES
-- =====================================================

-- Para testar, você pode executar estas queries como diferentes usuários:

-- Como owner/admin (deve funcionar):
-- INSERT INTO generated_coupons (code, percentage, brand, valid_until, max_uses, created_by, created_by_brand, nuvemshop_status)
-- VALUES ('TEST-OWNER-10', 10, 'TestBrand', NOW() + INTERVAL '30 days', 100, auth.uid(), 'TestBrand', 'pending');

-- Como partners-media (deve falhar):
-- INSERT INTO generated_coupons (code, percentage, brand, valid_until, max_uses, created_by, created_by_brand, nuvemshop_status)
-- VALUES ('TEST-PARTNER-10', 10, 'TestBrand', NOW() + INTERVAL '30 days', 100, auth.uid(), 'TestBrand', 'pending');

-- =====================================================
-- 8. INSTRUÇÕES DE ROLLBACK (se necessário)
-- =====================================================

/*
Para reverter essas mudanças (se necessário):

-- Remover as novas políticas
DROP POLICY IF EXISTS "Allow owners and admins to create coupons" ON generated_coupons;
DROP POLICY IF EXISTS "Allow owners and admins to update coupons" ON generated_coupons;

-- Recriar a política original para partners-media
CREATE POLICY "Allow partners-media to create coupons for their brand"
ON generated_coupons
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM user_profiles 
    WHERE user_profiles.id = auth.uid() 
    AND user_profiles.role = 'partners-media'
    AND user_profiles.assigned_brand = generated_coupons.brand
    AND user_profiles.approved = true
  )
  AND created_by = auth.uid()
  AND created_by_brand = brand
);
*/

-- =====================================================
-- 9. CONCLUSÃO
-- =====================================================

-- Após executar este script:
-- ✅ Partners-media NÃO podem mais criar cupons
-- ✅ Partners-media ainda podem visualizar cupons da sua marca
-- ✅ Owners e admins podem criar, visualizar e gerenciar todos os cupons
-- ✅ Sistema de permissões está mais restritivo e seguro
