-- Events received from GHL workflows when one of the funnel tags is added.
-- Raw payloads contain contact data and are intentionally service-role only.

CREATE TABLE IF NOT EXISTS public.ghl_funnel_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL DEFAULT 'contact_tag_added',
  stage_slug TEXT NOT NULL CHECK (
    stage_slug IN (
      'lead',
      'commockautomatico',
      'semmockautomatico',
      'solicitouorcamento',
      'solicitoumockupoficial',
      'emnegociacao',
      'negociofechado'
    )
  ),
  stage_name TEXT NOT NULL,
  contact_id TEXT NOT NULL,
  contact_name TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  contact_company_name TEXT,
  quantidade_pares NUMERIC,
  tags TEXT[] NOT NULL DEFAULT '{}',
  location_id TEXT,
  workflow_id TEXT,
  workflow_name TEXT,
  contact_created_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  raw_payload JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ghl_funnel_events_contact_stage
  ON public.ghl_funnel_events (contact_id, stage_slug);

CREATE INDEX IF NOT EXISTS idx_ghl_funnel_events_received_at
  ON public.ghl_funnel_events (received_at DESC);

ALTER TABLE public.ghl_funnel_events ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.ghl_funnel_events IS
  'Tag events received from GHL workflows for the A/B conversion funnels.';
