-- ============================================================
-- Registro de webhooks recusados (2026-09-04)
--
-- Motivo: entre 02/09 15:09 e 04/09 o funil ficou 42 h sem receber evento.
-- Os workflows do GHL nunca pararam -- 103 requisições por dia continuaram
-- chegando, e 97 delas voltavam 401 porque o secret deixou de bater. Como o
-- código só fazia `console.warn`, isso não gravava nada no banco nem virava
-- erro de runtime: a recusa era invisível para quem olhasse o Supabase, que é
-- onde o time olha. Levou dois dias para achar o que os logs da Vercel diriam
-- em cinco minutos.
--
-- Toda recusa passa a deixar rastro aqui, com o motivo. O que NUNCA entra:
-- o secret esperado, nem qualquer derivação dele. Do lado recebido guarda-se
-- só um prefixo de hash, que serve para responder "o GHL está mandando
-- sempre o mesmo token?" sem expor o token.
--
-- Consulta útil quando o funil ficar quieto:
--   SELECT motivo, count(*), max(received_at)
--   FROM webhook_rejections
--   WHERE received_at > now() - interval '24 hours'
--   GROUP BY 1 ORDER BY 2 DESC;
-- ============================================================

CREATE TABLE IF NOT EXISTS public.webhook_rejections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  rota TEXT NOT NULL,
  motivo TEXT NOT NULL,
  status INT NOT NULL,
  detalhe JSONB NOT NULL DEFAULT '{}'::jsonb,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_webhook_rejections_received
  ON public.webhook_rejections (received_at DESC);

CREATE INDEX IF NOT EXISTS idx_webhook_rejections_rota_motivo
  ON public.webhook_rejections (rota, motivo, received_at DESC);

COMMENT ON TABLE public.webhook_rejections IS
  'Webhooks recusados antes de virar evento. Existe porque um 401 silencioso deixou o funil 42h sem dado em 02-04/09/2026.';

ALTER TABLE public.webhook_rejections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read authenticated" ON public.webhook_rejections;
CREATE POLICY "read authenticated"
  ON public.webhook_rejections
  FOR SELECT
  TO authenticated
  USING (true);
